exit commited

diff --git a/.github/workflows/sonarqube-scan-template.yml b/.github/workflows/sonarqube-scan-template.yml
--- a/.github/workflows/sonarqube-scan-template.yml
+++ b/.github/workflows/sonarqube-scan-template.yml
@@ -161,7 +161,7 @@ jobs:
                 echo "✅ Quality Gate passed: $STATUS" >> $GITHUB_STEP_SUMMARY
               else
                 echo "❌ Quality Gate failed: $STATUS" >> $GITHUB_STEP_SUMMARY
-                exit 1  # Uncomment to fail the pipeline on gate failure
+                # exit 1  # Uncomment to fail the pipeline on gate failure
               fi
           else
             echo "⚠️ Gate check bypassed as per configuration (run-sonarqube-gate-check=no)." >> $GITHUB_STEP_SUMMARY
