Updated the code Check SonarQube Quality Gate

diff --git a/.github/workflows/sonarqube-scan-template.yml b/.github/workflows/sonarqube-scan-template.yml
--- a/.github/workflows/sonarqube-scan-template.yml
+++ b/.github/workflows/sonarqube-scan-template.yml
@@ -106,10 +106,9 @@ jobs:
           STATUS=$(curl -s -u ${{ secrets.SONAR_TOKEN }}: \
             "${{ secrets.SONAR_HOST_URL }}/api/qualitygates/project_status?projectKey=${{ inputs.projectKey }}" \
             | jq -r '.projectStatus.status')
-          echo "### Quality Gate Status: $STATUS" >> $GITHUB_STEP_SUMMARY
-          if [ "$STATUS" != "OK" ]; then
-            echo "Quality Gate failed!" >> $GITHUB_STEP_SUMMARY
-            exit 1
+          if [ "$STATUS" = "OK" ]; then
+            echo "Quality Gate passed ✅" >> $GITHUB_STEP_SUMMARY
+          else
+            echo "Quality Gate status: $STATUS ❌" >> $GITHUB_STEP_SUMMARY
+            # exit 1   # uncomment only if you want pipeline to fail
           fi
-
-
